FROM gcr.io/google-appengine/debian9:latest
COPY context/foo foo
WORKDIR /test
WORKDIR workdir
COPY context/foo .
RUN cp foo newfoo
WORKDIR /new/dir
ENV dir /another/new/dir
WORKDIR $dir/newdir
WORKDIR /
