FROM busybox

RUN adduser --disabled-password --gecos "" --uid 1000 user
RUN mkdir -p /home/user/foo
RUN chown -R user /home/user
RUN chmod 700 /home/user/foo
ADD Makefile /home/user/foo/Makefile
RUN chown -R user /home/user
