# Copyright 2018 Google, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Test to make sure the cache works properly
# If the image is built twice, /date should be the same in both images
# if the cache is implemented correctly

FROM alpine as base_stage

RUN mkdir foo && echo base_stage > foo/base

FROM base_stage as cached_stage

RUN echo cached_stage > foo/cache

FROM cached_stage as bug_stage

RUN echo bug_stage > foo/bug
RUN date > /date
