ARG REGISTRY=docker.io
ARG IMAGE=debian
ARG TAG=9.11
ARG WORD=hello
ARG W0RD2=hey

FROM ${REGISTRY}/${IMAGE}:${TAG} as stage1

# Should evaluate WORD and create /tmp/hello
ARG WORD
RUN touch /${WORD}

FROM ${REGISTRY}/${IMAGE}:${TAG}

COPY --from=stage1 /hello /tmp

# /tmp/hey should not get created without the ARG statement
# Use -d 0 to force a time change because of stat resolution
RUN touch -d 0 /tmp/${WORD2}
