name: Integration tests (Run)

on:
  pull_request:
    branches: ['master']

concurrency:
  group: int-test-run-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1

    - name: Run integration-test-run
      run: |
        make travis-setup
        make minikube-setup
        make integration-test-run
