name: Integration Tests Misc

on:
  pull_request:
    branches: ['master']

concurrency:
  group: int-test-mis-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      TRAVIS_BRANCH: ${{ github.head_ref }}
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1

    - name: Print Travis ENV vars
      run: |
        echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
        echo "TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}"
        echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"

    - name: Run integration-test-misc
      run : |
        make travis-setup
        make minikube-setup
        make integration-test-misc
