name: Integration tests (K8s)

on:
  pull_request:
    branches: ['master']

concurrency:
  group: int-test-k8s-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1

    - name: Run build-image-and-k8s-integration-test
      run: |
        make travis-setup
        make minikube-setup
        make k8s-executor-build-push
        make integration-test-k8s
