name: Unit tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3
      with:
        go-version: 1.17
    - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3

    - run: make test
