name: Unit tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

concurrency:
  group: unit-tests-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2

    - run: make test
